[package]
name = "range_union_find"
version = "0.1.0"
authors = ["rlee287 <rlee287@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"
sorted-vec = "0.5.2"
